load("@twigz//bazel:grammar.bzl", "twigz_pack")

package(default_visibility = ["//visibility:public"])

twigz_pack(
    name = "syntax_pack",
    grammars = [
        "@twigz//grammars:lua",
        "@twigz//grammars:luau",
    ],
)

filegroup(
    name = "syntax_pack_csrcs",
    srcs = [":syntax_pack"],
    output_group = "csrcs",
)

filegroup(
    name = "syntax_pack_scanners",
    srcs = [":syntax_pack"],
    output_group = "scanners",
)

filegroup(
    name = "syntax_registry_json",
    srcs = [":syntax_pack"],
    output_group = "registry_json",
)

genrule(
    name = "syntax_registry_zig",
    srcs = [":syntax_registry_json"],
    outs = ["registry.zig"],
    cmd = "$(execpath //bazel/tools/syntax-registry-zig) $(location :syntax_registry_json) $@",
    tools = ["//bazel/tools/syntax-registry-zig"],
)
